### ISSUE TITLE
Experience in shock buffet

### ISSUE THREAD

**Issue by jiaqiwang969** [AndreWeiner/naca0012_shock_buffet#3]
Hi, @[AndreWeiner](https://github.com/FlowModelingControl/naca0012_shock_buffet/commits?author=AndreWeiner)
I have followed your step, and do several simulation testing, in [Cascade](https://github.com/jiaqiwang969/DLR-buffet).
Here is my little experience: 
- use "hisa" in steady case, is fast to converge.
- Use rhoEnergyFoam to replace rhoCentralFoam, which is better, and the time is still efficient.
- Much better if GPU is acess.
- Change SAiddes to LES will see more detail about vortex & shock interaction.

Thanks

**Comment by AndreWeiner** [comment]
Hi @jiaqiwang969,
thanks for your feedback; it might be helpful at some point in the future. I'll close this issue for now, since there is nothing specific for me to do. If you feel the need for discussion, please re-open this issue.
Best, Andre
